title: <p align="center"> Rishikant Goswami </p>
logo: /assets/img/logo.png

description:
  <p align="center">

  <a href="https://github.com/Master-Rishi">GitHub</a>
  
  <br>   
  I'm Aspiring Machine Learning Engineer.Presently learning to build machine learning projects.
  <br>
  </p>



theme: jekyll-theme-minimal
