title: <p align="center"> Rishikant Goswami </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/Master-Rishi">GitHub</a>
  
  <br>   
  I'm Aspiring Machine Learning Engineer.
  <br>
  </p>



theme: jekyll-theme-minimal
